### PR TITLE
Added header files for new roof duality implementation

### PR DESCRIPTION
**Pull request by amahmudwave**
The roof duality is being re-implemented, these header files are going to be
used in the final version. This PR is to merge these header files early to make
the final PR smaller and also so that they can be reviewed early.

### CODE REVIEW

**Comment by amahmudwave** [comment]
@arcondello these can be reviewed early, since a single PR for roof duality would be too big to review at once. 
Thanks !

**Comment by arcondello** [comment]
This looks good to me, but I am increasingly thinking that this should live in a new package, `dwave-optimization` or similar, rather than dimod. @randomir , what do you think about us making that package for @amahmudwave to make PRs against? We can figure out structure etc as we go.

**Comment by randomir** [comment]
@arcondello, absolutely, that's exactly what I was proposing for #567.

We should just figure out the "low-levelness" of the package. It would be nice to be on the `dimod` level, with practically no Ocean dependencies. Then again, it'll probably be hard to stay like that as we keep adding hybrid support utils.

Re: name, I like it, but we should think about it in the light of "optimization vs. sampling" dichotomy.

**Comment by arcondello** [comment]
For dependencies, totally agree that low level would be ideal. I think it is likely that it will end up depending on dimod, specifically the C++ stuff, which brings numpy. #567 comes with [mip](https://pypi.org/project/mip/) and SciPy... I think we would want to prune that if possible. But yes, we'll have to work it as we go.

My inclination would be to make the repo, starting with `dwave-optimization`, and rename if needed?

**Comment by JoelPasvolsky** [comment]
Can you say more about what functionality would be in such a package. Do you mean a package for generic code optimization?

**Comment by arcondello** [comment]
For things like roof duality, the lower bounds in #567. Possibly would even include some of the stuff in dwave-binarycsp.

**Comment by arcondello** [comment]
Closing because this has moved to a new package

**Pull request closed without merging**
