### PR TITLE
Fix make_quadratic bug

### PR DESCRIPTION
**Pull request by arcondello**
Make quadratic handles square terms correctly now. Bug report came from https://support.dwavesys.com/hc/en-us/community/posts/360035719954-dimod-make-quadratic-returns-error

### CODE REVIEW

**Comment by rdisipio** [comment]
Hi,
  is there any timescale for this MR to be approved?

Cheers,
Riccardo

**Comment by arcondello** [comment]
Hey @rdisipio, I will go ahead and deploy a new version of dimod with the fix now

**Comment by rdisipio** [comment]
Hi,
  I updated my local installation and it seemed to go past the first error. However, now I have a bqm that looks like this:

```
BinaryQuadraticModel({'0': -13.6, '1': -3.4, '0*1': 25.2, '2': -1.5}, {('0', '1'): 5.0, ('0', '0*1'): -10.0, ('0', '2'): 12.1, ('1', '0*1'): -10.0, ('1', '2'): 1.9, ('0*1', '2'): 5.0}, 0.0, Vartype.BINARY)
```

If I try to solve the QUBO problem using the ```SimulatedAnnealingSampler```, I get a result out. On the other hand, if I try to solve on the QPU using a ```FixedEmbeddingComposite```, it complains about list indices:

```
Traceback (most recent call last):
  File "./nbody.py", line 197, in <module>
    results = qpu_sampler.sample(bqm, **solver_parameters).aggregate()
  File "/Users/disipio/dwave/lib/python3.7/site-packages/dwave/system/composites/embedding.py", line 403, in sample
    return super(LazyFixedEmbeddingComposite, self).sample(bqm, **parameters)
  File "/Users/disipio/dwave/lib/python3.7/site-packages/dwave/system/composites/embedding.py", line 202, in sample
    for v, chain in embedding.items()
  File "/Users/disipio/dwave/lib/python3.7/site-packages/dwave/system/composites/embedding.py", line 203, in <dictcomp>
    for u in chain}
TypeError: list indices must be integers or slices, not str
```

**Comment by arcondello** [comment]
Hi @rdisipio, can you send a larger snippet of your program? I suspect that your embedding does not match the BQM but would need to see more

**Comment by arcondello** [comment]
I think the problem is actually with
```
processor = dnx.chimera_graph(16, 16, 4).edges()
embedding = minorminer.find_embedding(source, processor)
```
you want to do
```
hardware_sampler = DWaveSampler()
embedding = minorminer.find_embedding(source, hardware_sampler.edgelist)
qpu_sampler = FixedEmbeddingComposite(hardware_sampler, embedding)
```
so that is respects the working graph of the actual QPU rather (which may be missing qubits/couplers).

**Comment by arcondello** [comment]
Ah, are you using an initial state? That might also be causing an issue

**Comment by rdisipio** [comment]
Uhm...I changed the code to:

```
hardware_sampler = DWaveSampler()
source = bqm.quadratic
embedding = minorminer.find_embedding(source, hardware_sampler.edgelist)
qpu_sampler = FixedEmbeddingComposite(hardware_sampler, embedding)
```

but I still get the same error. It seems to refer to a problem with the name of the qubits being strings (such as ```'0*1'```) rather than numbers.

**Comment by rdisipio** [comment]
Yes, I'm trying to reverse anneal. I set the initial state e.g. to:
```
[ (0,1), (1,0), (2,0) ]
```

**Comment by arcondello** [comment]
Ah, got it, try
```
initial_state = {v: 0 for v in set().union(*Q)}  # for the original problem

bqm = dimod.make_quadratic(Q, 5.0, dimod.BINARY)

for v in bqm:
   if v not in initial_state:
        initial_state[v] = random.choice((0, 1))
```
or similar

**Comment by rdisipio** [comment]
Ah ah! So I was setting fewer qubits in the initial state than required by the simplified bqm. Thanks for helping out!

**Comment by arcondello** [comment]
One last thing, you should check out [HigherOrderComposite](https://docs.ocean.dwavesys.com/projects/dimod/en/latest/reference/sampler_composites/higher_order_composites.html#dimod.reference.composites.higherordercomposites.HigherOrderComposite), it actually handles this case for you. You can just do

```
Q = { 
        ('0','0'):-13.6, ('1','1'):-3.4, ('2','2'):-1.5,
        ('1','0'):10.2, ('2','0'):12.1, ('2','1'):1.9, 
        ('0','1','1','2'):5.0,
    }

sampler = dimod.HigherOrderComposite(EmbeddingComposite(DWaveSampler()))
sampler.sample_hubo(Q, initial_state={v: 0 for v in set().union(*Q))
```

**Pull request merged**
