### PR TITLE
Add TrackingComposite

### LINKED ISSUE #481: A sampler for composites that will not sample but give access to modified problem
It would be cool to have a "sampler" that does not do sampling but gives access to the problem that is generated by the composite. 

I'm thinking something like
```
sampler = Composite(SaidSampler())
response = sampler.sample_ising(h,J,**kwargs)
response.bqm
response.h
response.j
```

and such.

### PR DESCRIPTION
**Pull request by arcondello**
Closes #481

### CODE REVIEW

**Comment by conta877** [comment]
whats the behavior when its sprinkled between composites? should there be a test for it?

**Comment by arcondello** [comment]
The information is tracked on the composite object. So they don't interact with each other.

**Comment by arcondello** [comment]
It does make things a bit awkward for nested composites, for instance
```
>>> sampler = RoofDualityComposite(TruncateComposite(TrackingComposite(ExactSolver())))
```
the inputs would need to be accessed with
```
>>> sampler.child.child.input
```
or, of course you can do
```
>>> tracking_sampler = TrackingComposite(ExactSolver())
>>> sampler = RoofDualityComposite(TruncateComposite(tracking_sampler))
>>> tracking_sampler.input
```

**Comment by conta877** [comment]
yeah... so then why are we doing a composite for tracking instead of a sampler object? I thought the idea was to be able to nest

**Comment by arcondello** [comment]
Because you still can access the nested objects, and because one is often interested in what happened between two composites.

**Comment by conta877** [comment]
I feel like we are in agreement here. I just think that there should be a test for what

```
>>> tracking_sampler = TrackingComposite(ExactSolver())
>>> sampler = RoofDualityComposite(TruncateComposite(tracking_sampler))
>>> tracking_sampler.input
```

and this use case should be in docs

**Pull request merged**
