### PR TITLE
fixes #697, fixed relabel variables as integers with no inplace

### LINKED ISSUE #697: bqm relabel variables as integers does not work when inplace=False
Wrong method is called when `inplace=False`

### PR DESCRIPTION
**Pull request by alexzucca90**
Closes #697

### CODE REVIEW

**Review by arcondello — APPROVED** [review]

**Comment by arcondello** [comment]
Actually, can we add a test that would have caught it?

**Comment by alexzucca90** [comment]
fixed the test, as it was awkwardly using `inplace=True` for an `inplace=False` operation. Should work now

**Comment by arcondello** [comment]
Now I am worried that we don't test `inplace=True`

**Comment by alexzucca90** [comment]
well, `inplace=True` is called inside `inplace=False` so it should actually raise the error

**Comment by arcondello** [comment]
That is true, although an implementation detail. We should have tests that are still valuable even if the implementation changes.

**Review by arcondello — APPROVED** [review]
Good catch, thanks

**Pull request merged**
