### PR TITLE
Ignore self-loops in DQM.add_linear_equality_constraint

### PR DESCRIPTION
**Pull request by arcondello**

### CODE REVIEW

**Review by rahmani15 — APPROVED** [review]

**Comment by hsadeghidw** [comment]
I had a bug in my original implementation -- or perhaps we need to decide what to do when the following happens:

`terms =  [(u, 0, 1.0), (u, 0, 1.0), (v, 0, 1.0]`

the expression above can be simplified to 

`terms =  [(u, 0, 2.0), (v, 0, 1.0]`

but the original implementation and the current one simply ignores one of the terms with the repeated variable/case combination.

**Review by hsadeghidw — CHANGES_REQUESTED** [review]
Add another test (like the random constraint tests) that has self-loops. I can add that as well.

**Comment by arcondello** [comment]
I did add a test with self loops?

**Comment by arcondello** [comment]
Also, currently I am pretty sure the case you describe is added as desired, but I can test that.

**Comment by hsadeghidw** [comment]
there is a test for self-loop, but I was saying that we can add a random one as well.

I noticed in my testing that if the variable-case are both repeated, one of the terms is ignored.

**Comment by arcondello** [comment]
Got it, I can add a test for that. Worth noting that unittests in general shouldn't be random :)

**Comment by hsadeghidw** [comment]
here are the two cases:

```
def case_1():
    num_variables = 4
    cases = np.random.randint(3, 6, size=num_variables)
    dqm_0 = dimod.DiscreteQuadraticModel()
    dqm = dimod.DiscreteQuadraticModel()
    for i in range(num_variables):
        dqm_0.add_variable(cases[i], i)
        dqm.add_variable(cases[i], i)
    x = dqm.variables

    expression1 = [(0, 0, 2), (1, 0, 2), (2, 1, 0), (3, 0, 8)]
    expression2 = [(0, 1, 2), (1, 1, 2), (2, 0, 0), (3, 1, 8)]
    expression = expression1 + expression2
    constant = np.random.randint(1, 10) * num_variables
    lagrange_multiplier = np.random.randint(1, 10)
    dqm.add_linear_equality_constraint(
        expression,
        lagrange_multiplier=lagrange_multiplier, constant=constant)

    expression_dict1 = {v: (c, b) for v, c, b in expression1}
    expression_dict2 = {v: (c, b) for v, c, b in expression2}

    for case_values in itertools.product(*(range(c) for c in cases)):
        state = {x[i]: case_values[i] for i in x}
        energy = dqm.energy(state) + lagrange_multiplier * constant ** 2
        s = constant
        for v, cv, bias in expression1:
            if expression_dict1[v][0] == state[v]:
                s += bias
        for v, cv, bias in expression2:
            if expression_dict2[v][0] == state[v]:
                s += bias
        assert (energy == lagrange_multiplier * s ** 2 + dqm_0.energy(state))


def case_2():
    num_variables = 4
    cases = np.random.randint(3, 6, size=num_variables)
    dqm_0 = dimod.DiscreteQuadraticModel()
    dqm = dimod.DiscreteQuadraticModel()
    for i in range(num_variables):
        dqm_0.add_variable(cases[i], i)
        dqm.add_variable(cases[i], i)
    x = dqm.variables

    expression1 = [(0, 0, 2), (1, 0, 2), (2, 1, 0), (3, 0, 8)]
    expression2 = [(0, 0, 2), (1, 0, 2), (2, 1, 0), (3, 0, 8)]
    expression = expression1 + expression2
    constant = np.random.randint(1, 10) * num_variables
    lagrange_multiplier = np.random.randint(1, 10)
    dqm.add_linear_equality_constraint(
        expression,
        lagrange_multiplier=lagrange_multiplier, constant=constant)

    expression_dict1 = {v: (c, b) for v, c, b in expression1}
    expression_dict2 = {v: (c, b) for v, c, b in expression2}

    for case_values in itertools.product(*(range(c) for c in cases)):
        state = {x[i]: case_values[i] for i in x}
        energy = dqm.energy(state) + lagrange_multiplier * constant ** 2
        s = constant
        for v, cv, bias in expression1:
            if expression_dict1[v][0] == state[v]:
                s += bias
        for v, cv, bias in expression2:
            if expression_dict2[v][0] == state[v]:
                s += bias
        assert (energy == lagrange_multiplier * s ** 2 + dqm_0.energy(state))

```
case_1 passes, case_2 fails.

**Comment by arcondello** [comment]
Right, it's not that a term is ignored, here is a smaller test case
```
    def test_self_loop3(self):
        dqm1 = dimod.DiscreteQuadraticModel()
        dqm2 = dimod.DiscreteQuadraticModel()

        dqm1.add_variable(5)
        dqm2.add_variable(5)

        lagrange_multiplier = 1
        constant = 0
        dqm1.add_linear_equality_constraint(
            [(0, 0, 2), (0, 0, 2)],
            lagrange_multiplier=lagrange_multiplier,
            constant=constant)

        dqm2.add_linear_equality_constraint(
            [(0, 0, 4)],
            lagrange_multiplier=lagrange_multiplier,
            constant=constant)

        np.testing.assert_array_equal(dqm1.get_linear(0), dqm2.get_linear(0))
```

The problem is in the linear step. So we do `lbias = lagrange_multiplier * biases[i] * (2 * constant + biases[i])` ([source](https://github.com/dwavesystems/dimod/blob/f3084e89c1ca288217b66b854fd8321743fc39d0/dimod/discrete/cydiscrete_quadratic_model.pyx#L74)). So we get
```
case1 == 1*2*(2*0+2) + 1*2*(2*0+2) == 8
case2 == 1*4*(2*0+4) == 16
```

So, the solution is to sort the variables/cases/biases on input and deduplicate. This obviously will have some performance implications. Though it will be `O(nlog(n))` in where `n` is the number of terms. This will be dominated by the `O(n**2)` operation which constructs the bqm.

**Comment by arcondello** [comment]
Ok, this time for real. @hsadeghidw , can you retest?

**Comment by hsadeghidw** [comment]
will do

**Review by hsadeghidw — APPROVED** [review]

**Comment by hsadeghidw** [comment]
passes all tests now

**Pull request merged**
