### PR TITLE
Add a scaling guide to the docs

### PR DESCRIPTION
**Pull request by arcondello**

### CODE REVIEW

**Comment by arcondello** [comment]
Ok, I just don't think nbsphinx is mature enough. I will remake this PR without it.

**Comment by JoelPasvolsky** [comment]
Are you seeing problems in CircleCI that you did not have when building locally?

**Comment by arcondello** [comment]
Yes, for instance you need pandoc installed for it to work. It's not such a huge dependency, but it's just one of a whole pile of dependencies needed.

It also doesn't play that nicely with pydata-sphinx-theme.

IMO, let's wait 6 months to see if it gets more adopted.

**Comment by JoelPasvolsky** [comment]
I'm not sure about keeping the JN here now: it means duplicate updating and is not tested.

**Comment by arcondello** [comment]
> I'm not sure about keeping the JN here now: it means duplicate updating and is not tested.

To be fair, the code itself is not tested either. I am fine to remove it, or I can add testing to circleci. IMO the latter is preferred for maintainability

**Review by JoelPasvolsky — APPROVED** [review]

**Pull request merged**
