### PR TITLE
multiplication_circuit bugfix

### PR DESCRIPTION
**Pull request by mhlr**
Carry bit of the most significant column of a row need to feed add to the most significant column of the next row.

### CODE REVIEW

**Comment by arcondello** [comment]
Can you add a test? No good deed goes unpunished. 

Also needs a release note.

**Comment by mhlr** [comment]
> Can you add a test? No good deed goes unpunished.

@arcondello The problem is that the bug only manifests for problems that are too large for the exact solver and and then it is pretty hit or miss on the QPU. Not sure how to make a good test for it

**Comment by arcondello** [comment]
My recommendation would be to generate a big one then feed some correct and incorrect solutions in and test that the energy is what you expect.

**Comment by mhlr** [comment]
Test and note added

**Review by arcondello — APPROVED** [review]

**Pull request merged**
